config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin_user, controllers: {
    sessions: "admin_user/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get '/users', to: redirect("/users/sign_up")
  end

  root to: 'public/recipes#top'

  namespace :admin_user do
    get '/' => 'recipes#top'
    resources :recipes do
      resources :reviews, only:[:create, :destroy]
    end
    resources :alcohols, only:[:index, :edit, :create, :destroy]
    patch  'alcohols/:id/edit' => 'alcohols#update'#URL変更のため別途記述
    resources :users, only:[:index, :show, :edit, :update]
    get "search" => "searches#search"
  end

  namespace :public do
    resources :recipes, only:[:index, :show] do
      resources :reviews, only:[:create, :destroy]
      resource :bookmarks, only:[:create, :destroy]
    end
    resource :user, only:[:show, :edit, :update]
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/quit' => 'users#quit'
    get "search" => "searches#search"
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true  #新規登録　名前
  validates :email, presence: true #新規登録   パスワード

  def get_profile_image(width, height)
	  unless profile_image.attached?
	    file_path = Rails.root.join('app/assets/images/no_image.jpg')
	    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
	  end
	  profile_image.variant(resize_to_limit: [width, height]).processed
	end
  # ゲストログインemail,nameランダム設定
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end

end

app/controllers/admin_user/alcohols_controller.rb
class AdminUser::AlcoholsController < ApplicationController

  layout 'admin_user/application'

  def index
    @alcohol = Alcohol.new
    @alcohols = Alcohol.all
  end

  def edit
    @alcohol = Alcohol.find(params[:id])
  end

  def create
    @alcohol = Alcohol.new(alcohol_params)
    if @alcohol.save
      redirect_to admin_user_alcohols_path
      flash[:notice] = "お酒登録完了"
    else
      @alcohols = Alcohol.all
      render :index
    end
  end

  def update
    @alcohol = Alcohol.find(params[:id])
    if @alcohol.update(alcohol_params)
      redirect_to admin_user_alcohols_path
      flash[:notice] = "お酒変更完了"
    else
      render :edit
    end
  end

  def destroy
    alcohol = Alcohol.find(params[:id])
    alcohol.destroy
    redirect_to admin_user_alcohols_path
  end

  private

  def alcohol_params
    params.require(:alcohol).permit(:name)
  end

end

app/controllers/admin_user/confirmations_controller.rb
# frozen_string_literal: true

class AdminUser::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin_user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class AdminUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin_user/passwords_controller.rb
# frozen_string_literal: true

class AdminUser::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin_user/recipes_controller.rb
class AdminUser::RecipesController < ApplicationController

  before_action :set_q,only: [:index, :search]
  layout 'admin_user/application'

  def new
    @recipe = Recipe.new
    #recipeに紐づく中間テーブルのインスタンス生成
    @recipe.recipe_genres.build
  end

  def index
    @alcohols = Alcohol.all
    # お酒タグに並び替え
    if params[:alcohol_id]
      @alcohol = Alcohol.find(params[:alcohol_id])
      @recipes = @alcohol.recipes.page(params[:page]).per(20)
    # 新着順に並び替え
    elsif params[:latest]
      @recipes = Recipe.latest.page(params[:page]).per(20)
    # 全てのレシピ
    else
      @recipes = Recipe.all.page(params[:page]).per(20)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
    #recipeに紐づく中間テーブルのインスタンス生成
    @recipe.recipe_genres.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to admin_user_recipe_path(@recipe)
      flash[:notice] = "レシピ登録完了"
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to admin_user_recipe_path(@recipe)
      flash[:notice] = "編集完了"
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to admin_user_recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :explanation, :ingredient, :procedure, :image, alcohol_ids: [])
  end

  def set_q
    @q_recipe = Recipe.ransack(params[:q])
  end

end

app/controllers/admin_user/registrations_controller.rb
# frozen_string_literal: true

class AdminUser::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_user/searches_controller.rb
class AdminUser::SearchesController < ApplicationController

  layout 'admin_user/application'

  before_action :set_q,only: [:index, :search]

  def search
    # ユーザー一覧ページからの検索
    if params[:q][:view_name] == "user"
      @users = @q_user.result(distinct: true)
    # レシピ一覧ページからの検索
    else
      @recipes = @q_recipe.result(distinct: true)
    end
  end

  private

  def set_q
    @q_user = User.ransack(params[:q])
    @q_recipe = Recipe.ransack(params[:q])
  end

end

app/controllers/admin_user/sessions_controller.rb
# frozen_string_literal: true

class AdminUser::SessionsController < Devise::SessionsController
  layout 'admin_user/application'

  def after_sign_in_path_for(resource)
    flash[:notice] = "ログインしました"
    admin_user_recipes_path
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = " ログアウトしました"
    root_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin_user/unlocks_controller.rb
# frozen_string_literal: true

class AdminUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_user/users_controller.rb
class AdminUser::UsersController < ApplicationController

  before_action :set_q,only: [:index, :search]
  layout 'admin_user/application'

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_user_path
    flash[:notice] = "ステータス変更完了"
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end

  def set_q
    @q_user = User.ransack(params[:q])
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_recipes_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/helpers/admin_user/alcohols_helper.rb
module AdminUser::AlcoholsHelper
end

app/helpers/admin_user/recipes_helper.rb
module AdminUser::RecipesHelper
end

app/helpers/admin_user/searches_helper.rb
module AdminUser::SearchesHelper
end

app/helpers/admin_user/users_helper.rb
module AdminUser::UsersHelper
end

app/views/admin_user/users/_index.html.erb
<!--会員一覧（テーブル）-->
<div class="bg-light">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>ステータス</th>
      </tr>
    </thead>
  <% users.each do |user| %>
    <tbody>
      <tr onclick='window.location="<%= '/admin_user/users/' + user.id.to_s %>"' role="link">
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <% if user.is_deleted == true %>
          <td>退会</td>
        <% else %>
          <td>有効</td>
        <% end %>
      </tr>
    </tbody>
  <% end %>
  </table>
</div>

app/views/admin_user/users/edit.html.erb
<div class="container">
  <!--タイトル-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <h2><strong><%= @user.name %>様の会員ステータス変更</strong></h2>
    </div>
  </div>
  <!--ステータス変更-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= form_with model: @user, url: admin_user_user_path(@user), method: :patch do |f| %>
        <%= f.radio_button :is_deleted, false %> <%= f.label :is_active, "有効" %>
        <%= f.radio_button :is_deleted, true %> <%= f.label :is_active, "退会" %>
        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
  <!--戻るボタン-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to admin_user_users_path, class: 'text-link' do %>
        <strong><i class="fas fa-chevron-circle-left"></i>一覧ページに戻る<i class="fas fa-chevron-circle-left"></i></strong>
      <% end %>
    </div>
  </div>

</div>

app/views/admin_user/users/index.html.erb
<din class="container">
  <!--タイトル-->
  <div class="row">
    <div class="col-lg-12 mt-5 mb-3 text-center">
      <h2>ユーザー一覧</h2>
    </div>
  </div>
  <!--ユーザー部分検索-->
  <div class="row">
    <div class="col-lg-12 mb-3 pr-5 text-right">
      <p class="pr-5">ユーザー検索</p>
      <%= render "admin_user/searches/form", q: @q_user, view_name: "user" %>
    </div>
  </div>
  <!--会員一覧（テーブル）-->
  <div class="row  justify-content-center">
    <div class="col-lg-10 mt-3 mb-3 text-center">
      <%= render "admin_user/users/index", users: @users %>
    </din>
  </din>
  <!--ページネーション-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3">
      <%= paginate @users %>
    </din>
  </din>

</din>

app/views/admin_user/users/show.html.erb
<div class="container">
  <!--タイトル-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <h2><%= @user.name %>様の会員情報</h2>
    </div>
  </div>
  <!--会員詳細（テーブル）-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <div class="bg-light">
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
              <th>ステータス変更画面</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @user.id %></td>
              <td><%= @user.name %></td>
              <td><%= @user.email %></td>
              <% if @user.is_deleted == true %>
                <td>退会</td>
              <% else %>
                <td>有効</td>
              <% end %>
              <td>
                <%= link_to edit_admin_user_user_path(@user) do %>
                  <i class="fas fa-edit text-success"></i>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--ユーザーコメント一覧-->
  <div class="row">
    <% @reviews.each do |review| %>
      <div class="col-lg-4 mt-3 mb-3">
        <div class="bg-light p-2">
          <%= link_to public_recipe_review_path(review.recipe, review), class: "text-dark", method: :delete do %>
              <p><i class="fas fa-trash-alt"></i>削除</p>
            <% end %>
          <%= review.text %>
        </div>
      </div>
    <% end %>
  </div>
  <!--戻るボタン-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to admin_user_users_path, class: 'text-link' do %>
        <strong><i class="fas fa-chevron-circle-left"></i>一覧ページに戻る<i class="fas fa-chevron-circle-left"></i></strong>
      <% end %>
    </div>
  </div>

</div>