config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin_user, controllers: {
    sessions: "admin_user/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get '/users', to: redirect("/users/sign_up")
  end

  root to: 'public/recipes#top'

  namespace :admin_user do
    get '/' => 'recipes#top'
    resources :recipes do
      resources :reviews, only:[:create, :destroy]
    end
    resources :alcohols, only:[:index, :edit, :create, :destroy]
    patch  'alcohols/:id/edit' => 'alcohols#update'#URL変更のため別途記述
    resources :users, only:[:index, :show, :edit, :update]
    get "search" => "searches#search"
  end

  namespace :public do
    resources :recipes, only:[:index, :show] do
      resources :reviews, only:[:create, :destroy]
      resource :bookmarks, only:[:create, :destroy]
    end
    resource :user, only:[:show, :edit, :update]
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/quit' => 'users#quit'
    get "search" => "searches#search"
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	has_many :recipe_genres, dependent: :destroy
	has_many :alcohols, through: :recipe_genres, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :reviews, dependent: :destroy

	has_one_attached :image

	validates :image, presence: true                  #画像
	validates :name, length: { in: 2..30 }            #レシピ名
	validates :recipe_genres, presence: true          #お酒の選択
	validates :explanation, length: { in: 1..100 }    #コメント
	validates :ingredient, length: { maximum: 1000 }  #食材
	validates :procedure, length: { maximum: 2500 }   #手順

	# 新着順・ランキング順
	scope :latest, -> {order(created_at: :desc)}
	scope :star_count, -> {left_joins(:reviews).group(:id).order("avg(reviews.rate) DESC")}
	#ランキング平均値の記述 BigDecimalから整数少数へ変換
	def reviews_avg
		reviews.average(:rate).to_s.to_f.round(1)
	end

	def get_image(width, height)
	  unless image.attached?
	    file_path = Rails.root.join('app/assets/images/no_image.jpg')
	    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
	  end
	  image.variant(resize_to_limit: [width, height]).processed
	end
	#bookmarkテーブルにユーザーidが存在しているかを検証
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

end

app/controllers/admin_user/alcohols_controller.rb
class AdminUser::AlcoholsController < ApplicationController

  layout 'admin_user/application'

  def index
    @alcohol = Alcohol.new
    @alcohols = Alcohol.all
  end

  def edit
    @alcohol = Alcohol.find(params[:id])
  end

  def create
    @alcohol = Alcohol.new(alcohol_params)
    if @alcohol.save
      redirect_to admin_user_alcohols_path
      flash[:notice] = "お酒登録完了"
    else
      @alcohols = Alcohol.all
      render :index
    end
  end

  def update
    @alcohol = Alcohol.find(params[:id])
    if @alcohol.update(alcohol_params)
      redirect_to admin_user_alcohols_path
      flash[:notice] = "お酒変更完了"
    else
      render :edit
    end
  end

  def destroy
    alcohol = Alcohol.find(params[:id])
    alcohol.destroy
    redirect_to admin_user_alcohols_path
  end

  private

  def alcohol_params
    params.require(:alcohol).permit(:name)
  end

end

app/controllers/admin_user/confirmations_controller.rb
# frozen_string_literal: true

class AdminUser::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin_user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class AdminUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin_user/passwords_controller.rb
# frozen_string_literal: true

class AdminUser::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin_user/recipes_controller.rb
class AdminUser::RecipesController < ApplicationController

  before_action :set_q,only: [:index, :search]
  layout 'admin_user/application'

  def new
    @recipe = Recipe.new
    #recipeに紐づく中間テーブルのインスタンス生成
    @recipe.recipe_genres.build
  end

  def index
    @alcohols = Alcohol.all
    # お酒タグに並び替え
    if params[:alcohol_id]
      @alcohol = Alcohol.find(params[:alcohol_id])
      @recipes = @alcohol.recipes.page(params[:page]).per(20)
    # 新着順に並び替え
    elsif params[:latest]
      @recipes = Recipe.latest.page(params[:page]).per(20)
    # 全てのレシピ
    else
      @recipes = Recipe.all.page(params[:page]).per(20)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
    #recipeに紐づく中間テーブルのインスタンス生成
    @recipe.recipe_genres.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to admin_user_recipe_path(@recipe)
      flash[:notice] = "レシピ登録完了"
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to admin_user_recipe_path(@recipe)
      flash[:notice] = "編集完了"
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to admin_user_recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :explanation, :ingredient, :procedure, :image, alcohol_ids: [])
  end

  def set_q
    @q_recipe = Recipe.ransack(params[:q])
  end

end

app/controllers/admin_user/registrations_controller.rb
# frozen_string_literal: true

class AdminUser::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_user/searches_controller.rb
class AdminUser::SearchesController < ApplicationController

  layout 'admin_user/application'

  before_action :set_q,only: [:index, :search]

  def search
    # ユーザー一覧ページからの検索
    if params[:q][:view_name] == "user"
      @users = @q_user.result(distinct: true)
    # レシピ一覧ページからの検索
    else
      @recipes = @q_recipe.result(distinct: true)
    end
  end

  private

  def set_q
    @q_user = User.ransack(params[:q])
    @q_recipe = Recipe.ransack(params[:q])
  end

end

app/controllers/admin_user/sessions_controller.rb
# frozen_string_literal: true

class AdminUser::SessionsController < Devise::SessionsController
  layout 'admin_user/application'

  def after_sign_in_path_for(resource)
    flash[:notice] = "ログインしました"
    admin_user_recipes_path
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = " ログアウトしました"
    root_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin_user/unlocks_controller.rb
# frozen_string_literal: true

class AdminUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_user/users_controller.rb
class AdminUser::UsersController < ApplicationController

  before_action :set_q,only: [:index, :search]
  layout 'admin_user/application'

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_user_path
    flash[:notice] = "ステータス変更完了"
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end

  def set_q
    @q_user = User.ransack(params[:q])
  end

end

app/helpers/admin_user/alcohols_helper.rb
module AdminUser::AlcoholsHelper
end

app/helpers/admin_user/recipes_helper.rb
module AdminUser::RecipesHelper
end

app/helpers/admin_user/searches_helper.rb
module AdminUser::SearchesHelper
end

app/helpers/admin_user/users_helper.rb
module AdminUser::UsersHelper
end

app/views/admin_user/recipes/_form.html.erb
<!--レシピ画像-->
<div class="row">
  <div class="col-lg-12 mb-3 text-center">
    <p><strong><%= f.label :image, "レシピ画像" %></strong></p>
    <%= f.file_field :image, class: "col-4",  accept: "image/*" %>
  </div>
</div>
<!--レシピタイトルフォーム-->
<div class="row">
  <div class="col-lg-12 mb-3 text-center">
    <p><strong><%= f.label :name,"レシピ名"%></strong></p>
    <%= f.text_field :name, class: "col-lg-6" %>
  </div>
</div>
<!--タグ付け-->
<div class="row">
  <div class="col-lg-12 mb-3 text-center">
    <p><strong><%= f.label :name,"お酒" %></strong></p>
    <%= f.collection_check_boxes(:alcohol_ids, Alcohol.all, :id, :name, include_hidden: false ) %>
  </div>
</div>
<!--レシピコメントフォーム-->
<div class="row">
  <div class="col-lg-12 mb-3 text-center">
    <p><strong><%= f.label :explanation, "レシピコメント" %></strong></p>
    <%= f.text_area :explanation, size: "70x5" %>
  </div>
</div>
<!--食材と調理法フォーム-->
<div class="row">
  <div class="col-lg-6 mb-3 text-center">
    <p><strong><%= f.label :ingredient, "食材" %></strong></p>
    <%= f.text_area :ingredient, size: "70x15" %>
  </div>
  <div class="col-lg-6 mb-3 text-center">
    <p><strong><%= f.label :procedure, "調理手順" %></strong></p>
    <%= f.text_area :procedure, size: "70x15" %>
  </div>
</div>
<!--登録ボタン-->
<div class="row">
  <div class="col-12 mb-3 text-center">
    <%= f.submit '登録' %>
  </div>
</div>

app/views/admin_user/recipes/_index.html.erb
<!--レシピ一覧-->
<% recipes.each do |recipe| %>
  <div class="col-lg-4  mb-5 text-center">
    <div class="user-bg">
      <%= link_to admin_user_recipe_path(recipe.id),class: 'text-link' do %>
        <p><%= image_tag recipe.get_image(200,200),class: 'image-mypage' %></p>
        <p>レシピ名: <%= recipe.name %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin_user/recipes/_show.html.erb
<!--レシピ写真-->
<div class="row">
  <div class="col-lg-12 mb-3 text-center">
    <%= image_tag recipe.get_image(400,400),class: "image-show" %>
  </div>
</div>
<!--レシピコメント-->
<div class="row">
  <div class="col-lg-12 text-center">
    <p class="comment-show"><%= recipe.explanation %></p>
  </div>
</div>
<!--食材と調理法-->
<div class="row mx-auto">
  <div class="col-lg-6">
    <p class="text-bg">
      <strong>食材</strong></br>
      <span class="text">
        <%= safe_join(recipe.ingredient.split("\n"),tag(:br)) %>
      </span>
    </p>
  </div>
  <div class="col-lg-6">
    <p class="text-bg">
      <strong>作り方</strong></br>
      <span class="text">
        <%= safe_join(recipe.procedure.split("\n"),tag(:br)) %>
      </span>
    </p>
  </div>
</div>

app/views/admin_user/recipes/edit.html.erb
<div class="container">
  <!--タイトル＋エラーメッセージ-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <h2><strong>レシピ編集</strong></h2>
      <%= render 'layouts/errors', obj: @recipe %>
    </div>
  </div>
  <!--編集フォーム-->
  <%= form_with model: @recipe, url: admin_user_recipe_path, method: :patch do |f| %>
    <%= render "admin_user/recipes/form", f: f %>
  <% end %>
  <!--戻るボタン-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to admin_user_recipes_path, class: 'text-link' do %>
        <strong><i class="fas fa-chevron-circle-left"></i>一覧ページに戻る<i class="fas fa-chevron-circle-left"></i></strong>
      <% end %>
    </div>
  </div>

</div>

app/views/admin_user/recipes/index.html.erb
<div class="container">
  <!--タグ検索＋レシピ部分検索＋並び替え-->
  <div class="row">
    <div class="col-lg-6 mt-3 mb-3 text-center">
      <h4>お酒の種類</h4>
      <% @alcohols.each do |alcohol| %>
        <%= link_to admin_user_recipes_path(alcohol_id: alcohol.id), class: "text-dark" do %>
          <i class="fas fa-beer text-warning"></i><%= alcohol.name %>
        <% end %>
      <% end %>
    </div>
    <div class="col-lg-6 mt-3 mb-3 text-center">
      <p>レシピ名検索</p>
      <%= render "admin_user/searches/form", q: @q_recipe, view_name: "recipe" %>
      <%= link_to '新しい順', admin_user_recipes_path(latest: "true"), class: "btn btn-outline-danger" %>
    </div>
  </div>
  <!--レシピ新規作成リンク-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to new_admin_user_recipe_path,class: 'text-info' do %>
        <h4><i class="fas fa-plus"></i>レシピ追加</h4>
      <% end %>
    </div>
  </div>
  <!--タイトル表示（お酒or新着orすべて）-->
  <div class="row">
    <div class="col-lg-12 mt-5 mb-3 text-center">
      <h2>
        <% if @alcohol.present? %>
          <%= @alcohol.name %>に合うおすすめレシピ
        <% elsif params[:latest].present? %>
          すべてのレシピ＜新着順＞
        <% else %>
          すべてのレシピ
        <% end %>
      </h2>
    </div>
  </div>
  <!--レシピ一覧-->
  <div class="row">
    <%= render "admin_user/recipes/index", recipes: @recipes %>
  </div>
  <!--ページネーション-->
  <div class="row">
    <div class="col-lg-12 mt-5 mb-3 text-center">
      <%= paginate @recipes %>
    </div>
  </div>

</div>

app/views/admin_user/recipes/new.html.erb
<div class="container">
  <!--タイトル＋エラーメッセージ-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <h2><strong>新規レシピ</strong></h2>
      <%= render 'layouts/errors', obj: @recipe %>
    </div>
  </div>
  <!--編集フォーム-->
  <%= form_with model: @recipe, url: admin_user_recipes_path, method: :post do |f| %>
    <%= render "admin_user/recipes/form", f: f %>
  <% end %>
  <!--戻るボタン-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to admin_user_recipes_path, class: 'text-link' do %>
        <strong><i class="fas fa-chevron-circle-left"></i>一覧ページに戻る<i class="fas fa-chevron-circle-left"></i></strong>
      <% end %>
    </div>
  </div>

</div>

app/views/admin_user/recipes/show.html.erb
<div class="container">
  <!--編集or削除リンク-->
  <div class="row">
    <div class="col-lg-6 text-center mt-3 mb-3 ">
      <%= link_to edit_admin_user_recipe_path(@recipe) ,class: "text-success" do %>
        <i class="fas fa-edit text-success"></i>編集
      <% end %>
    </div>
     <div class="col-lg-6 text-center mt-3 mb-3 ">
      <%= link_to admin_user_recipe_path(@recipe), method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "text-secondary" do %>
        <i class="fas fa-trash-alt text-dark"></i>削除する
      <% end %>
    </div>
  </div>
  <!--タイトルとタグ-->
  <div class="row">
    <div class="col-lg-12 mt-5 mb-1 p-2 text-center">
      <h2>
        <strong><%= @recipe.name %></strong>
      </h2>
      <strong>合うお酒</strong>
      <% @recipe.alcohols.each do |alcohol| %>
        /<%= safe_join(alcohol.name.split("\n"),tag(:br)) %>
      <% end %>
    </div>
  </div>
  <!--レシピ詳細-->
  <%= render "admin_user/recipes/show", recipe: @recipe %>
  <!--戻るボタン-->
  <div class="row">
    <div class="col-lg-12 mt-3 mb-3 text-center">
      <%= link_to admin_user_recipes_path, class: 'text-link' do %>
        <strong><i class="fas fa-chevron-circle-left"></i>一覧ページに戻る<i class="fas fa-chevron-circle-left"></i></strong>
      <% end %>
    </div>
  </div>

</div>